version: "3.8"

services:
  base-datos:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      MYSQL_ROOT_PASSWORD: root1
    networks:
      - mi-red
networks:
  mi-red:
    driver: overlay
