version: "3.8"

services:
  servicio-web:
    image: image-php-apache
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - base-datos_mi-red  # Aquí se especifica la red a la que se conectará el servicio web
    volumes:
      - type: bind
        source: /home/elb/Despliegues/index.php
        target: /var/www/html/index.php
networks:
  base-datos_mi-red:
    external: true  # Aquí se define la red externa, si ya está creada
    name: base-datos_mi-red


